[platformio]
default_envs = esp32-c3-supermini

[env:esp32-c3-supermini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 460800
board_build.flash_mode = dio

build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D AGENTLIGHT_PIN_RED=4
  -D AGENTLIGHT_PIN_YELLOW=5
  -D AGENTLIGHT_PIN_GREEN=6
  -D AGENTLIGHT_ACTIVE_LOW=0

